language: python
sudo: required
dist: trusty

addons:
  apt:
    sources: &commonsources
    packages: &commonpackages
    - cmake
    - cmake-data
    - python-pyqt4
    - python3-pyqt4

# before_install:
# command to install dependencies
install:
  - pip install -r requirements.txt

# before_script:

script:
    - make test

# runs independent of 'script' failure/success
# after_script:


notifications:
  email:
    on_success: change
    on_failure: change

after_success:
- coveralls

branches:
  except:
    - gh-pages

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
